[#46800] Adding MaestroWebformInherit to os2forms_forloeb.module
OS2Forms/os2forms_forloeb pull request #100
Opened 2021-12-01 09:46 UTC by mBoegvald

This change is needed for the user to be able to use the maestro task 'WebformInherit'.

Attached webforms and flow for test.

[hjemmearbejde_flow.txt](https://github.com/OS2Forms/os2forms_forloeb/files/7632728/hjemmearbejde_flow.txt)
[Aftale om hjemmearbejde.txt](https://github.com/OS2Forms/os2forms_forloeb/files/7632729/Aftale.om.hjemmearbejde.txt)
[AMR vurdering.txt](https://github.com/OS2Forms/os2forms_forloeb/files/7632730/AMR.vurdering.txt)
[Samlet leder.txt](https://github.com/OS2Forms/os2forms_forloeb/files/7632731/Samlet.leder.txt)
[Samlet leder 2.txt](https://github.com/OS2Forms/os2forms_forloeb/files/7632732/Samlet.leder.2.txt)

2021-12-02 08:47 UTC, agger-magenta approved these changes

2021-12-06 09:38 UTC, lats1 requested changes

2021-12-06 09:38 UTC, lats1 commented on os2forms_forloeb.module
> +    if ($templateTask && ($templateTask['tasktype'] == 'MaestroWebformMultiple' || $templateTask['tasktype'] == 'MaestroWebformInherit')) {
You should consider defining the task type names as constants on the task type classes instead of referring by strings. This would allow changes of the name in only one place.
Also in this if condition, you are checking 3 things with parentheses around the last checks. Consider cleaning it up with something like `if ($templateTask && $this->isMultipleTaskType($templateTask['tasktype'])`

2021-12-06 09:43 UTC, agger-magenta commented on os2forms_forloeb.module
> +    if ($templateTask && ($templateTask['tasktype'] == 'MaestroWebformMultiple' || $templateTask['tasktype'] == 'MaestroWebformInherit')) {
An alternative would be to submit a pull request towards [this issue](https://www.drupal.org/project/maestro/issues/3243510) in Maestro so we could avoid the not very elegant but currently necessary reimplementation of this hook.

That's more work, however, and in the meantime it does seem like a good idea to write this as cleanly as possible.

2021-12-06 13:57 UTC, mBoegvald commented on os2forms_forloeb.module
> +    if ($templateTask && ($templateTask['tasktype'] == 'MaestroWebformMultiple' || $templateTask['tasktype'] == 'MaestroWebformInherit')) {
We can't use `$this` in the hook. 
Instead i created a function, which returns an array of custom task-types.

I guess the code could be simplified even more, like:
`if ($templateTask && in_array($templateTask['tasktype'], os2forms_forloeb_get_custom_task_types)) {`
- I don't think this would improve readability though.

2021-12-07 11:30 UTC, lats1 approved these changes

2021-12-07 12:57 UTC, merged