Task A: Implemented redirect route for task console to get better UX for users
OS2Forms/os2forms_forloeb pull request #130
Opened 2022-03-29 14:21 UTC by andriyun

Custom path: `/execute-foloeb-task`

The ability to refer to the specific task in email is possible via token, for example 
`/execute-foloeb-task?token=XebF7BbNosDZNM-GNDP7ADH0vaPbR74pLSf8pnXCalE`

2022-03-31 08:04 UTC, rimi-itk requested changes
Looks very good! Nice and clean solution.

Some comments and suggestions added.

2022-03-31 08:04 UTC, rimi-itk commented on src/ForloebTaskConsole.php
> +  }
Is it possible to get the queue record directly from the token without having to load and iterate over all queues and submissions, i.e. something like

```
// Warning: Pseudocode ahead!
$submission = $this->entityTypeManager->getStorage('webform_submission')->findByToken($token);
return NULL !== $submission
  ? $this->entityTypeManager->getStorage('maestro_queue')->findBySubmission($submission)
  : NULL;

2022-04-01 14:49 UTC, andriyun commented on os2forms_forloeb.routing.yml
> +  path: 'execute-foloeb-task'
Fixed

2022-04-01 14:52 UTC, andriyun commented on src/Controller/ForloebTaskConsoleController.php
> +    }
Added early return

2022-04-01 15:08 UTC, andriyun commented on src/ForloebTaskConsole.php
> +  }
I don't think it's possible in an easy way. I can not find a direct connection between `maestro_queue` and `webform_submission` to implement this kind of lookup.

By idea, `maestro_queue` can have different handlers and reference to webform submission is on of them.

2022-04-04 08:38 UTC, andriyun commented
Hi @rimi-itk 
Unfortunately, I can not merge this PR to develop branch.
Maybe you have access, and can do this for me?

2022-04-04 10:22 UTC, rimi-itk commented
Sorry, @andriyun, I don't have permissions to merge, but maybe @madsnorgaard or @agger-magenta can help us?

2022-04-04 10:36 UTC, agger-magenta commented
It's strange, but I can't seem to merge this either. @madsnorgaard, can you do it?

2022-04-04 10:38 UTC, merged

2022-04-04 10:38 UTC, madsnorgaard commented
Squashed and merged.

2022-04-28 11:29 UTC, andriyun commented on src/ForloebTaskConsole.php
> +  }
I finally found a way to get it https://github.com/OS2Forms/os2forms_forloeb/pull/131/commits/f92e668e5af4671df9666a9e9928b6a7a47806dc