OS2FORMS-371 Added token for easy getting os2forms execute task link in mail handlers
OS2Forms/os2forms_forloeb pull request #131
Opened 2022-04-05 06:00 UTC by andriyun

Followup for PR130
New token ['webform_submission:'os2forms_forloeb_execute_task]

2022-04-05 06:17 UTC, rimi-itk approved these changes

2022-05-02 09:38 UTC, rimi-itk requested changes
Looks good. `===` should be used for comparisons rather than just `==`.

2022-05-02 09:38 UTC, rimi-itk commented on os2forms_forloeb.module
> +    if ($token && $token == $entity->getToken()) {
For consistency, we should always use `===` for comparison.

2022-05-02 09:38 UTC, rimi-itk commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +      if ($token == $webform_submission->getToken()) {
Use `===` here.

2022-05-17 10:55 UTC, rimi-itk commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +      if ($token == $webform_submission->getToken()) {
@andriyun, do you have local commits that haven't beed pushed?

2022-05-17 12:52 UTC, andriyun commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +      if ($token == $webform_submission->getToken()) {
@rimi-itk I just pushed fixes for these two changes you requested

2022-05-17 12:53 UTC, andriyun commented on os2forms_forloeb.module
> +    if ($token && $token == $entity->getToken()) {
Fixed

2022-05-17 14:53 UTC, rimi-itk approved these changes
Very good job.

2022-05-17 14:57 UTC, rimi-itk commented
Hmm … I cannot merge either, @andriyun. @mBoegvald & @madsnorgaard, can you help us out?

2022-05-17 18:32 UTC, madsnorgaard commented
I will squash and merge. Hope you are all well!

2022-05-17 18:32 UTC, merged