Preparing for new release
OS2Forms/os2forms_forloeb pull request #132
Opened 2022-05-18 08:01 UTC by andriyun

2022-05-18 09:26 UTC, rimi-itk requested changes
A few minor changes needed.

2022-05-18 09:26 UTC, rimi-itk commented on os2forms_forloeb.module
> +}
Implementations of `hook_entity_access` should return an instance of `AccessResultInterface` (cf. https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21entity.api.php/function/hook_entity_access/9.1.x), so I think we should return `AccessResult::neutral()` here.

2022-05-18 09:26 UTC, rimi-itk commented on os2forms_forloeb.module
> +      return \Drupal\Core\Access\AccessResult::allowed();
Add `use Drupal\Core\Access\AccessResult` rather than using the FQN here.

2022-05-19 16:10 UTC, madsnorgaard commented on os2forms_forloeb.module
> +      return \Drupal\Core\Access\AccessResult::allowed();
Haven't tested. LGTM.

2022-05-19 16:14 UTC, madsnorgaard reviewed
LGTM. No tests done during review.

2022-05-20 10:14 UTC, andriyun commented on os2forms_forloeb.module
> +}
Added this fix in #PR133

2022-05-20 10:14 UTC, andriyun commented on os2forms_forloeb.module
> +      return \Drupal\Core\Access\AccessResult::allowed();
Added this fix in https://github.com/OS2Forms/os2forms_forloeb/pull/133

2022-06-22 13:01 UTC, rimi-itk approved these changes

2022-06-27 09:00 UTC, merged