OS2FORMS-371 Fixed review feedback
OS2Forms/os2forms_forloeb pull request #133
Opened 2022-05-20 10:13 UTC by andriyun

Since it's not possible to add fixes directly yo #132 we have to use separate PR

2022-05-20 10:32 UTC, rimi-itk requested changes
I've explained my previous comment on https://github.com/OS2Forms/os2forms_forloeb/pull/132.

2022-05-20 10:32 UTC, rimi-itk commented on os2forms_forloeb.module
> +      return AccessResult::neutral();
I think you've misunderstood my comment https://github.com/OS2Forms/os2forms_forloeb/pull/132#discussion_r875674197 – and on reading it again I can understand that.

We should still return `AccessResult::allowed()` when the token is valid, and my suggestion is to add `return AccessResult::natural()` *at the end of the function* to always return a `AccessResult` (rather than implicitly returning `null`).

2022-05-30 06:42 UTC, andriyun commented on os2forms_forloeb.module
> +      return AccessResult::neutral();
Oh.. right.
I misunderstood your comment.

I added changes that should cover your request. Please check again :)

2022-05-30 07:13 UTC, rimi-itk approved these changes

2022-05-31 11:49 UTC, andriyun commented
@madsnorgaard Can you help me with merging?
Thank you :)

2022-05-31 14:17 UTC, merged