DW-568: Added support for inheriting values without creating a submission
OS2Forms/os2forms_forloeb pull request #135
Opened 2022-08-19 10:22 UTC by rimi-itk

2022-09-05 13:21 UTC, stanbellcom requested changes

2022-09-05 13:21 UTC, stanbellcom commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +  private static function getTaskValuesSessionKey(int $queueID) {
i suggest to call it formatTaskValuesSessionKey, as it in fact is formating the provided key, not getting it from elsewhere

2022-09-05 13:21 UTC, stanbellcom commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +   */
param/returns docs missing

2022-09-05 13:21 UTC, stanbellcom commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +   */
param/returns docs missing

2022-09-05 13:21 UTC, stanbellcom commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +   */
param/returns docs missing

2022-09-22 13:41 UTC, rimi-itk commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +  private static function getTaskValuesSessionKey(int $queueID) {
Fixed in https://github.com/OS2Forms/os2forms_forloeb/pull/135/commits/e70e74020e620234bdd0d31bd45276a4a8b4991a.

2022-09-22 13:41 UTC, rimi-itk commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +   */
Fixed in https://github.com/OS2Forms/os2forms_forloeb/pull/135/commits/2832a962a0afb4fad3fa06fe2fef21d0318a98bd.

2022-09-22 13:41 UTC, rimi-itk commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +   */
Fixed in https://github.com/OS2Forms/os2forms_forloeb/pull/135/commits/2832a962a0afb4fad3fa06fe2fef21d0318a98bd.

2022-09-22 13:41 UTC, rimi-itk commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +   */
Fixed in https://github.com/OS2Forms/os2forms_forloeb/pull/135/commits/2832a962a0afb4fad3fa06fe2fef21d0318a98bd.

2022-10-10 11:50 UTC, stanbellcom approved these changes

2022-10-25 11:04 UTC, rimi-itk commented
@stanbellcom, after intensive testing I've made a small, but crucial change to the code (https://github.com/OS2Forms/os2forms_forloeb/pull/135/commits/9e86111d5c316bdcbdee332e3427a5e4b2f70040).

2022-11-14 11:35 UTC, stanbellcom approved these changes

2022-11-16 08:44 UTC, merged