Composer cleanup
OS2Forms/os2forms_forloeb pull request #143
Opened 2023-01-05 08:31 UTC by martinyde

- Add dependency on os2forms/os2forms

2023-01-05 15:39 UTC, rimi-itk requested changes
Very good. Some minor changes suggested.

2023-01-05 15:39 UTC, rimi-itk commented on .github/workflows/pr.yml
> +        run: git diff --exit-code origin/develop -- CHANGELOG.md && exit 1 || exit 0
We should use `${{ github.base_ref }}` (cf. https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) rather than `develop` here since we may be making a pull request against a branch other than `develop` (see https://github.com/itk-dev/os2forms_selvbetjening/blob/develop/.github/workflows/pr.yaml#L19 for an example use).

2023-01-05 15:39 UTC, rimi-itk commented on composer.json
> +        "entityQuery reference JOINs should specify target_type (https://www.drupal.org/project/dynamic_entity_reference/issues/3120952#comment-14141038) - required by drupal/workflow_participants":
We could, I think, make it more clear why we're patching a module we don't directly require by adding a command above the patch, i.e. something that really stands out, e.g.

```json
      },
      "//": "Note: drupal/dynamic_entity_reference is required by drupal/workflow_participants",
      "drupal/dynamic_entity_reference": {
        …
      }
```

2023-01-06 08:47 UTC, rimi-itk approved these changes

2023-01-31 13:09 UTC, skifter approved these changes

2023-01-31 13:23 UTC, merged