Adding WIP webforms and Maestro templates.
OS2Forms/os2forms_forloeb pull request #26
Opened 2021-04-14 11:17 UTC by madsnorgaard

2021-04-14 12:10 UTC, agger-magenta approved these changes
Ja, lad os endelig få de eksempler ind!

2021-04-15 08:18 UTC, lats1 requested changes

2021-04-15 08:18 UTC, lats1 commented on src/Plugin/EngineTasks/MaestroSelectContentTask.php
> +        $content_type_options = array(""=>"All Content Types");
I guess an empty string as key in an array will work, but why not use "all" or something similar for better understanding? And also, should "All Content Types" be translated?

2021-04-16 10:26 UTC, madsnorgaard commented on os2forms_forloeb.module
> +//  );
This code has been removed as it is not necessary for the review workflow.

2021-04-16 10:27 UTC, madsnorgaard commented on src/Plugin/EngineTasks/MaestroSelectContentTask.php
> +        $content_type_options = array(""=>"All Content Types");
Changes committed per comment. All good input.

2021-04-20 07:02 UTC, lats1 approved these changes

2021-04-20 07:06 UTC, merged