Adding automated CI checks to project.
OS2Forms/os2forms_forloeb pull request #54
Opened 2021-05-05 16:43 UTC by madsnorgaard

2021-05-05 19:20 UTC, madsnorgaard commented
This PR relies on this PR #55 to be merged. Once these two pull requests are merged, we can close all open issues from the review.

2021-05-06 11:44 UTC, lats1 requested changes

2021-05-06 11:44 UTC, lats1 commented on .travis.yml
> +- composer update os2forms/os2forms_forloeb
You could maybe replace this with the following commands:
`composer config repositories.os2forms_forloeb '{"type": "path", "url": "../os2forms_forloeb", "symlink": "false"}'`
`composer require os2forms/os2forms_forloeb`

2021-05-06 12:04 UTC, madsnorgaard commented on .travis.yml
> +- composer update os2forms/os2forms_forloeb
I will add:
`composer config repositories.os2forms_forloeb '{"type":"path","url":"../os2forms_forloeb","symlink":"false"}'`

2021-05-06 13:45 UTC, merged