44236 uninstall update manager per default
OS2Forms/os2forms_forloeb pull request #61
Opened 2021-08-16 13:05 UTC by madsnorgaard

This change will uninstall the Update Manager core module per default.

2021-08-17 12:47 UTC, agger-magenta approved these changes
Ser fint ud!

2021-08-20 09:20 UTC, lats1 requested changes

2021-08-20 09:20 UTC, lats1 commented on os2forms_forloeb.install
> +  \Drupal::service('module_installer')->install($module_list);
Shouldn't this be `\Drupal::service('module_installer')->uninstall($module_list);` ?

2021-08-24 13:08 UTC, madsnorgaard commented
After discussion with @lats1 we are closing this PR as it is not good practice in the repo with multiple companies and teams working together.

2021-08-24 13:08 UTC, closed without merging