Update translations for OS2forms Forløb installation.
OS2Forms/os2forms_forloeb pull request #68
Opened 2021-09-01 19:08 UTC by madsnorgaard

2021-09-08 09:34 UTC, lats1 submitted a review, later dismissed

2021-09-08 09:36 UTC, lats1 commented
Over 45,000 additions? Does this translation file in this module translate something else than whats included in this module?

2021-09-22 10:18 UTC, lats1 requested changes
This is still ongoing right?

2021-09-28 12:44 UTC, madsnorgaard commented
Closing this as wrong file used in commit. 

NEW PR: https://github.com/OS2Forms/os2forms_forloeb/pull/71

2021-09-28 12:44 UTC, closed without merging