[#46780] Removed all parts of HK/Holstebro, to make the webform gener…
OS2Forms/os2forms_forloeb pull request #91
Opened 2021-11-05 15:10 UTC by mBoegvald

…ic and reusable for everyone.

2021-11-05 16:36 UTC, madsnorgaard requested changes
Still a few bits and pieces to follow up up:
https://github.com/OS2Forms/os2forms_forloeb/search?q=hk
https://github.com/OS2Forms/os2forms_forloeb/search?q=holstebro

2021-11-08 08:17 UTC, mBoegvald commented
@madsnorgaard I'm pretty sure, that what your search is finding, is how the 'develop' branch looks before the merge. I searched the file and i can't find anywhere, where HK/Holstebro hasn't been removed. If you go to my branch and search, it will probably (hopefully) show the same for you :-)

2021-11-08 08:23 UTC, madsnorgaard approved these changes

2021-11-10 08:41 UTC, lats1 approved these changes

2021-11-10 13:52 UTC, merged