[#46800] Created new task-type for inheriting webform in flow
OS2Forms/os2forms_forloeb pull request #92
Opened 2021-11-23 14:10 UTC by mBoegvald

This is not thoroughly tested, but this is at least a first iteration of the new task-type.

2021-11-24 12:08 UTC, mBoegvald commented
This MR is ready for review i'd say.

2021-11-24 12:10 UTC, agger-magenta commented
I'll look at it then!

2021-11-24 12:11 UTC, mBoegvald commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +
If we could avoid inserting form-elements that are already part of the MaestroWebformTask it would be nice.
The reason for adding these things is, that i needed another field `$form['inherit_webform_unique_id']`, but adding that field, meant that the form would remove all the other fields.

2021-11-24 12:46 UTC, agger-magenta requested changes
Nogle få kommentarer, generelt ser det fint ud!

2021-11-24 12:46 UTC, agger-magenta commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +
Stupid question, but can't you call the `getTaskEditForm` on the superclass/the `parent` object and then only add the field you need? In that way this function would 1) be a lot shorter and 2) avoid forking the functionality of Maestro's webform task, which might conceivably change in the future.

2021-11-24 12:46 UTC, agger-magenta commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +    $task['data']['skip_webform_handlers'] = $form_state->getValue('skip_webform_handlers');
Once again, is there a reason for not calling the `parent` and adding the handling of the inheritance stuff?

2021-11-24 12:46 UTC, agger-magenta commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +    // This var is a placeholder for a value set by the user - it's the task's 'unique_id'
It is in fact the unique id of the webform submission we're inheriting the fields from.

2021-11-24 12:46 UTC, agger-magenta commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +    if (!$webform_submission) {
Spørgsmål: Hvis denne task helt skal kunne erstatte `WebformMultiple` skal den kunne arve *flere* submission unique IDs - en kommasepareret liste eller (om muligt) en liste af felter eller noget.

I så fald skal den jo nok kunne håndtere, at et eller flere af disse unique IDs  ikke har en submission jfr. et ønske fra ITK om at kunne håndtere, at der "mangler" en submission i et flow.

Men så er kommentaren om at "Predecessors MUSt have submissions with webforms attached." ikke aktuel længere.

2021-11-24 17:00 UTC, mBoegvald commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +
I never got this working, but yes, that would be way better.

2021-11-24 17:17 UTC, mBoegvald commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +    if (!$webform_submission) {
Ift. funktionaliteten med at kunne arve flere submissions (på én gang), er det ikke noget der skal med i denne "udgave". Det er dog relevant at genbesøge.

Det er muligt at det kunne være en god idé at sørge for at submissions ikke er nødvendige. Jeg har rodet lidt rundt med diverse Webfoms og stødt ind i mange forskellige cases, så jeg er lidt i tvivl om de ville "brokke" sig, over at mangle noget data

2021-11-25 08:31 UTC, agger-magenta commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +    if (!$webform_submission) {
Det er OK!

Jeg tænker måske vi kan prøve at fejle på en "pænere" måde her, selv hvis vi ikke vil acceptere en formular, der ikke er udfyldt.

2021-11-25 08:31 UTC, agger-magenta commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +    if (!$webform_submission) {
Men det må du selv styre, jeg resolver denne del af samtalen :slightly_smiling_face:

2021-11-25 08:36 UTC, agger-magenta commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +
We do it here, e.g.: https://github.com/OS2Forms/os2forms_egir/blob/main/src/Feeds/Fetcher/KeycloakAuthFetcher.php#L41

I think something along those lines should work here too and would be better, as you say.

2021-11-25 11:03 UTC, mBoegvald commented
The PR has been updated with the mentioned improvements, I'm removing the Draft status and await final approval.

I have attached the flow and the webforms I've used to test it.

[Hjemmearbejde_flow.txt](https://github.com/OS2Forms/os2forms_forloeb/files/7602379/Hjemmearbejde_flow.txt)
[Aftale om hjemmearbejde.txt](https://github.com/OS2Forms/os2forms_forloeb/files/7602380/Aftale.om.hjemmearbejde.txt)
[Aftale om hjemmearbejde - samlet leder.txt](https://github.com/OS2Forms/os2forms_forloeb/files/7602381/Aftale.om.hjemmearbejde.-.samlet.leder.txt)
[Aftale om hjemmearbejde - samlet leder 2.txt](https://github.com/OS2Forms/os2forms_forloeb/files/7602382/Aftale.om.hjemmearbejde.-.samlet.leder.2.txt)
[Aftale om hjemmearbejde - AMR vurdering.txt](https://github.com/OS2Forms/os2forms_forloeb/files/7602383/Aftale.om.hjemmearbejde.-.AMR.vurdering.txt)

2021-11-25 12:36 UTC, agger-magenta commented
Ja, nu ser det godt ud!

2021-11-25 12:37 UTC, agger-magenta approved these changes

2021-11-25 16:32 UTC, rimi-itk requested changes
Looks good. A few changes are required. Note that I've added a comment on line 108, but this comment is hidden inside the previously resolved conversation on this line.

2021-11-25 16:32 UTC, rimi-itk commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +      '#default_value' => isset($task['data']['inherit_webform_unique_id']) ? $task['data']['inherit_webform_unique_id'] : '',
Using `??` here (cf. https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op) will make this a little easier to read.

2021-11-25 16:32 UTC, rimi-itk commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +    if (!$webform_submission) {
`$webform_submission` will be undefined here if `$sid` is falsy. Use if `!isset($webform_submission)` (or `empty($webform_submission)`) as the condition here.

2021-11-25 16:32 UTC, rimi-itk commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +        "Predecessors MUSt have submissions with webforms attached."
Typo in `MUSt` (should be `must`).

2021-11-25 16:32 UTC, rimi-itk commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +      \Drupal::logger('os2forms_forloeb')->error(
Consider using dependency injection for the logger if possible, However, I'm not sure if this is easy with `MaestroWebformTask` so we may have to live with using the static `logger` method.

2021-11-26 08:56 UTC, mBoegvald commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +      \Drupal::logger('os2forms_forloeb')->error(
Maestro is not using dependency injection, and we just reuse their way of handling logging. 
If you have any suggestions as to how, we can take a look at it?

2021-11-26 09:02 UTC, mikkelricky commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +      \Drupal::logger('os2forms_forloeb')->error(
When Maestro is not using dependency injection we'll just leave this as it is.

2021-11-26 09:15 UTC, rimi-itk requested changes
I missed the missing error handling in my first review. 

Please don't force push changes! This makes it harder to review changes.

2021-11-26 09:15 UTC, rimi-itk commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +    foreach ($webform_submission->getData() as $key => $value) {
You need to handle the case when `$webform_submission` is not set, i.e. by returning early. Just logging the error is not enough.

2021-11-26 09:34 UTC, mBoegvald commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +    foreach ($webform_submission->getData() as $key => $value) {
I changed line 109-111 to:
`return Drupal::logger('os2forms_forloeb')->error(
        "Predecessors must have submissions with webforms attached."
 );`

I'm wondering in which scenario we would use this task-type without having a submission. I don't see how we would ever get to an `WebformInheritTask` without having posted a submission earlier in the flow (as the whole functionality of this task-type is to get earlier submission's data).

2021-11-26 09:46 UTC, rimi-itk commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +    foreach ($webform_submission->getData() as $key => $value) {
I think you're missing a `git push` …

2021-11-26 09:49 UTC, mBoegvald commented on src/Plugin/EngineTasks/MaestroWebformInheritTask.php
> +    foreach ($webform_submission->getData() as $key => $value) {
Yes, sorry. I haven't pushed yet, I didn't test it before writing the comment, so it got a bit delayed, my bad.

2021-11-26 09:51 UTC, rimi-itk approved these changes

2021-11-26 11:22 UTC, merged