Fix to bug on default purge setting not saving.
OS2Forms/os2forms_forloeb pull request #99
Opened 2021-12-01 07:46 UTC by madsnorgaard

Bug fix to enable override of default purge time period.

2021-12-06 09:24 UTC, lats1 requested changes

2021-12-06 09:24 UTC, lats1 commented on os2forms_forloeb.module
> +  if ($save_webform) {
Where does the `$save_webform` variable come from? I don't think it's defined or set anywhere. On another node, the convention for variable naming in php projects is to use camel case.

2021-12-07 15:08 UTC, madsnorgaard commented on os2forms_forloeb.module
> +  if ($save_webform) {
Point taken and we have added a bit more extensive logic to this feature. 

In terms of naming standards in Drupal and PHP this should be the documentation - [Documentation on naming standards for variables:](https://www.drupal.org/docs/develop/standards/coding-standards#naming) 

_Variables should be named using lowercase, and words should be separated either with uppercase characters (example: $lowerCamelCase) or with an underscore (example: $snake_case). Be consistent; do not mix camelCase and snake_case variable naming inside a file._

2021-12-08 07:20 UTC, lats1 requested changes

2021-12-08 07:20 UTC, lats1 commented on os2forms_forloeb.module
> +        }
As I see it, this is equal to
```
if (TRUE) {
    $webform->save();
}
```
So the webform will always be saved at this point.
Is there a situation where `$save_webform` would have another value than `TRUE`? If so there should probably be some logic that changes the value of `$save_webform`. If the webform always should be saved at this point the check should probably be omitted.

On another point, could the call to the `$webform->save()`  method go wrong?

2021-12-08 08:06 UTC, madsnorgaard commented on os2forms_forloeb.module
> +        }
Good point Lars. I have removed the check and it is more minimal and will always save changes.

2021-12-08 11:04 UTC, lats1 approved these changes

2021-12-08 11:28 UTC, merged